/**
 * @file sntp_gettimeofday.c
 * @brief SNTP-backed gettimeofday() implementation for STM32
 *
 * This file provides the _gettimeofday() syscall that Newlib's time()
 * function depends on. It bridges Newlib's time() to the SNTP software
 * clock maintained by sntp_client.c.
 *
 * By putting this in a separate file (not syscalls.c), we ensure it
 * won't be lost if syscalls.c is regenerated by CubeMX.
 *
 * Compile this in Core/Src and link BEFORE syscalls.o in CMakeLists.txt
 * so this strong symbol takes precedence over CubeMX's weak definition.
 */

#include <time.h>
#include <sys/time.h>

/* Forward declaration: provided by packet_forwarder/sntp_client.c */
extern time_t sntp_get_utc(void);

/**
 * @brief Provide system time to Newlib via SNTP software clock
 *
 * This is the syscall that Newlib's time() function uses internally.
 * After SNTP sync, it returns real UTC. Before sync, returns 0.
 *
 * @param[out] tv   timeval struct to fill (tv_sec = UTC epoch, tv_usec = 0)
 * @param[in]  tz   timezone (ignored)
 * @return 0 on success
 */
int _gettimeofday(struct timeval *tv, void *tz)
{
    (void)tz;
    if (tv) {
        tv->tv_sec  = sntp_get_utc();
        tv->tv_usec = 0;
    }
    return 0;
}
